name: Commit Calendar
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # 매일 자정에 실행
      
permissions:
  contents: write 
jobs:
  generate-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 커밋 히스토리를 가져오기
      
      - name: Generate commit data
        run: |
          mkdir -p .github/scripts
          # 저장소에 .github/scripts/calendar.py 파일이 없으면 생성
          if [ ! -f .github/scripts/calendar.py ]; then
            echo "Creating calendar.py script"
            cat > .github/scripts/calendar.py << 'EOL'
