name: Commit Calendar


on:
  push:
    branches:
      - main

jobs:
  generate-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate commit calendar SVG
        run: |
          git log --since="30 days ago" --pretty=format:'%ad' --date=short > commits.txt
          python3 .github/scripts/calendar.py

      - name: Commit and push SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add commit-calendar.svg
          git commit -m "Update commit calendar"
          git push
